apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
  namespace: production
type: Opaque
stringData:
  mongodb-uri: "mongodb://admin:CHANGE_THIS_PASSWORD@mongodb-service.production.svc.cluster.local:27017/productdb?authSource=admin"