apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: production